name: pyspn
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - ca-certificates=2025.7.15
  - importlib-metadata=7.0.1
  - libcxx=19.1.7
  - libffi=3.4.4
  - ncurses=6.5
  - openssl=3.0.17
  - pip=24.2
  - python=3.8.20
  - readline=8.3
  - setuptools=75.1.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - appdirs==1.4.3
      - appnope==0.1.4
      - arff==0.9
      - astroid==2.3.3
      - atomicwrites==1.3.0
      - attrs==19.3.0
      - backcall==0.1.0
      - black==18.9b0
      - bleach==3.1.0
      - click==7.0
      - coverage==5.0.3
      - cycler==0.10.0
      - cython==0.29.15
      - debugpy==1.5.1
      - decorator==4.4.1
      - defusedxml==0.6.0
      - entrypoints==0.3
      - ipykernel==5.1.4
      - ipython==7.12.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - isort==4.3.21
      - jedi==0.16.0
      - jinja2==2.11.1
      - joblib==0.14.1
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==5.3.4
      - jupyter-console==6.1.0
      - jupyter-core==4.6.2
      - kiwisolver==1.1.0
      - lazy-object-proxy==1.4.3
      - liac-arff==2.4.0
      - line-profiler==5.0.0
      - markupsafe==1.1.1
      - matplotlib==3.1.3
      - mccabe==0.6.1
      - mistune==0.8.4
      - more-itertools==8.2.0
      - mypy==0.761
      - mypy-extensions==0.4.3
      - nbconvert==5.6.1
      - nbformat==5.0.4
      - notebook==6.0.3
      - numpy==1.18.1
      - packaging==25.0
      - pandas==1.1.5
      - pandocfilters==1.4.2
      - parso==0.6.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==7.0.0
      - pluggy==0.13.1
      - prometheus-client==0.7.1
      - prompt-toolkit==3.0.3
      - ptyprocess==0.6.0
      - py==1.8.1
      - pybind11==3.0.1
      - pygments==2.5.2
      - pylint==2.4.4
      - pyparsing==2.4.6
      - pyrsistent==0.15.7
      - pytest==5.3.5
      - pytest-cov==2.8.1
      - python-dateutil==2.8.1
      - pytz==2025.2
      - pyzmq==18.1.1
      - qtconsole==4.6.0
      - rope==0.16.0
      - scipy==1.4.1
      - send2trash==1.5.0
      - six==1.14.0
      - terminado==0.8.3
      - testpath==0.4.4
      - toml==0.10.0
      - tomli==2.3.0
      - tornado==6.0.3
      - traitlets==4.3.3
      - typed-ast==1.4.1
      - typing-extensions==3.7.4.1
      - wcwidth==0.1.8
      - webencodings==0.5.1
      - widgetsnbextension==3.5.1
      - wrapt==1.11.2
      - zipp==2.2.0
